version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    assignees:
      - matthiasharzer
    labels:
      - Dependencies
    allow:
      - dependency-type: direct
    commit-message:
      prefix: chore
    groups:
      gomod:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    assignees:
      - matthiasharzer
    labels:
      - Dependencies
    commit-message:
      prefix: chore
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: "docker"
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    assignees:
      - matthiasharzer
    labels:
      - Dependencies
    commit-message:
      prefix: chore
    groups:
      docker:
        patterns:
          - "*"
        update-types:
          - minor
          - patch