### GET request to example server
GET https://examples.http-client.intellij.net/get
  ?generated-in=GoLand

### Create Room
POST http://localhost:8080/create-room

### Subscribe to room
POST http://localhost:8080/subscribe
Content-Type: application/json

{
  "roomId": "KE64C7kR"
}
